[WIP] Parse mkvmerge's json output

diff --git a/mkv-transcode-flac b/mkv-transcode-flac
--- a/mkv-transcode-flac
+++ b/mkv-transcode-flac
@@ -7,7 +7,7 @@
 # A BASH script that transcodes all FLAC tracks of a matroska file to Ogg Vorbis
 # while preserving the track's name and language and it's default and forced flags as well as its delay.
 #
-# Requires mktemp, mkvmerge, mkvextract and oggenc (with FLAC decoder enabled)
+# Requires mktemp, mkvmerge, mkvextract, oggenc (with FLAC decoder enabled) and jq
 #
 # Usage:
 # chmod +x mkv-transcode-flac
@@ -37,34 +37,43 @@ hash mktemp 2>/dev/null || { echo >&2 "Error: Command mktemp not found"; exit 1;
 hash mkvmerge 2>/dev/null || { echo >&2 "Error: Command mkvmerge not found"; exit 1; }
 hash mkvextract 2>/dev/null || { echo >&2 "Error: Command mkvextract not found"; exit 1; }
 hash oggenc 2>/dev/null || { echo >&2 "Error: Command oggenc not found"; exit 1; }
+hash jq 2>/dev/null || { echo >&2 "Error: Command jq not found"; exit 1; }
+
+
+verbose=1
+
+yellow="\e[0;33m"
+reset="\e[0m"
+
+log() {
+	if [ $verbose = 1 ]; then
+		echo -e "\n$yellow$1$reset\n"
+	fi
+}
 
 
 file_name=$1
 
 tmp_dir=$(mktemp -d)
 
-trap 'rm -r "$tmp_dir"' EXIT
-
-option_file_name="$tmp_dir/options_file"
+# FIXME
+# trap 'rm -r "$tmp_dir"' EXIT
 
 IFS='
 '
 
-tracks=$(LANG=en_US.utf8 LANGUAGE=en_US.utf8 mkvmerge --identify-verbose "$file_name" | grep -E "(A_FLAC|A_PCM)")
+log "LANG=en_US.utf8 LANGUAGE=en_US.utf8 mkvmerge --identify --identification-format json \"$file_name\" | jq --raw-output --compact-output \".tracks[]\""
+tracks=$(LANG=en_US.utf8 LANGUAGE=en_US.utf8 mkvmerge --identify --identification-format json "$file_name" | jq --raw-output --compact-output ".tracks[]")
 
+options=""
 track_ids_string=""
 for track in $tracks; do
-	track_id=""
-	[[ "$track" =~ Track\ ID\ ([0-9]+) ]] &&
-		track_id=${BASH_REMATCH[1]}
-	[[ "$track" =~ language:([a-z]+) ]] &&
-		language=${BASH_REMATCH[1]}
-	[[ "$track" =~ track_name:([^ ]+) ]] &&
-		track_name=${BASH_REMATCH[1]}
-	[[ "$track" =~ default_track:([0-1]) ]] &&
-		default_track=${BASH_REMATCH[1]}
-	[[ "$track" =~ forced_track:([0-1]) ]] &&
-		forced_track=${BASH_REMATCH[1]}
+	codec_id=$(echo "$track" | jq --raw-output ".properties.codec_id")
+	track_id=$(echo "$track" | jq --raw-output ".id")
+	language=$(echo "$track" | jq --raw-output ".properties.language")
+	track_name=$(echo "$track" | jq --raw-output ".properties.track_name")
+	default_track=$(echo "$track" | jq --raw-output ".properties.default_track")
+	forced_track=$(echo "$track" | jq --raw-output ".properties.forced_track")
 
 	ext=""
 	if [[ "$track" =~ A_FLAC ]]; then
@@ -73,20 +82,30 @@ for track in $tracks; do
 		ext="pcm"
 	fi
 
+	if [[ "$ext" == "" ]]; then
+		continue
+	fi
+
 	if [[ "$track_id" == "" ]]; then
 		continue
 	fi
 
+	log "mkvextract timecodes_v2 \"$file_name\" \"$track_id:$tmp_dir/$track_id.ts\""
 	mkvextract timecodes_v2 "$file_name" "$track_id:$tmp_dir/$track_id.ts"
+
+	log "mkvextract tracks \"$file_name\" \"$track_id:$tmp_dir/$track_id.$ext\""
 	mkvextract tracks "$file_name" "$track_id:$tmp_dir/$track_id.$ext"
+
+	log "oggenc --quality=6 -o \"$tmp_dir/$track_id.ogg\" \"$tmp_dir/$track_id.$ext\""
 	oggenc --quality=6 -o "$tmp_dir/$track_id.ogg" "$tmp_dir/$track_id.$ext"
+
+	log "rm \"$tmp_dir/$track_id.$ext\""
 	rm "$tmp_dir/$track_id.$ext"
 
 	track_ids_string="$track_ids_string,$track_id"
 	delay=$(sed -n "2p" "$tmp_dir/$track_id.ts")
 
-	echo "--audio-tracks" >> "$option_file_name"
-	echo "0" >> "$option_file_name"
+	options="$options --audio-tracks 0"
 	if [[ "$track_name" != "" ]]; then
 		track_name=${track_name/\\s/\ }  # replace '\s' with ' '
 		track_name=${track_name/\\2/\"}  # replace '\2' with '"'
@@ -94,31 +113,29 @@ for track in $tracks; do
 		track_name=${track_name/\\h/#}   # replace '\h' with '#'
 # 		track_name=${track_name/\\\\/\\} # replace '\\' with '\' doesn't work
 		track_name=$(echo "$track_name" | sed -r 's/(flac|pcm)/Ogg Vorbis/i')
-		echo "--track-name" >> "$option_file_name"
-		echo "0:$track_name" >> "$option_file_name"
+		options="$options --track-name 0:$track_name"
 	fi
 	if [[ "$language" != "" ]]; then
-		echo "--language" >> "$option_file_name"
-		echo "0:$language" >> "$option_file_name"
+		options="$options --language 0:$language"
 	fi
 	if [[ "$default_track" != "" ]]; then
-		echo "--default-track" >> "$option_file_name"
-		echo "0:$default_track" >> "$option_file_name"
+		options="$options --default-track 0:$default_track"
 	fi
 	if [[ "$forced_track" != "" ]]; then
-		echo "--forced-track" >> "$option_file_name"
-		echo "0:$forced_track" >> "$option_file_name"
+		options="$options --forced-track 0:$forced_track"
 	fi
 	if [[ $delay != 0 ]]; then
-		echo "--sync" >> "$option_file_name"
-		echo "0:$delay" >> "$option_file_name"
+		options="$options --sync 0:$delay"
 	fi
-	echo "$tmp_dir/$track_id.ogg" >> "$option_file_name"
+	options="$options $tmp_dir/$track_id.ogg"
 done
 track_ids_string=${track_ids_string:1} # remove first comma
 
 if [[ "$track_ids_string" != "" ]]; then
-	mkvmerge -o "${file_name%.*} [Ogg Vorbis].mkv" --audio-tracks "!$track_ids_string" "$file_name" "@$option_file_name"
+	# FIXME
+	log "set +o histexpand"
+	log "mkvmerge -o \"${file_name%.*} [Ogg Vorbis].mkv\" --audio-tracks \"!$track_ids_string\" \"$file_name\" $options"
+	mkvmerge -o "${file_name%.*} [Ogg Vorbis].mkv" --audio-tracks "!$track_ids_string" "$file_name" $options
 else
 	echo "No flac or pcm stream found, doing nothing"
 fi
